import { finding, SEVERITY } from "../lib/findings.mjs";
import { renderIndex } from "../generators/gen-index.mjs";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

export const meta = { id: "index-drift", tier: "advanced", reqId: "G4" };

// Normalize line endings (CRLF/LF) and trailing whitespace so the comparison is not flaky on
// Windows/CI checkouts where git may rewrite line endings.
const norm = (s) => s.replace(/\r\n/g, "\n").replace(/\s+$/, "");

/**
 * G4 (Gold): INDEX.md is generated from library.json + component frontmatter (gen-index) and
 * drift-checked - a hand-edited generated INDEX is an error (Standard sec 2.6 G4). The native
 * manifests and manifest.generated.json are already drift-checked by U8; this adds INDEX.
 * Advanced tier, so it is a Gold burndown item until the plugin declares advanced.
 */
export function check(ctx) {
  const p = path.join(ctx.root, "INDEX.md");
  if (!existsSync(p)) {
    return [finding(meta.id, SEVERITY.ERROR, "INDEX.md is missing; at Gold it is generated by gen-index and drift-checked (Standard sec 2.6 G4). Generate it: node scripts/generators/gen-index.mjs . --write", { file: "INDEX.md", reqId: meta.reqId })];
  }
  let onDisk;
  try {
    onDisk = readFileSync(p, "utf8");
  } catch (e) {
    return [finding(meta.id, SEVERITY.ERROR, `INDEX.md could not be read: ${e.message}`, { file: "INDEX.md", reqId: meta.reqId })];
  }
  if (norm(onDisk) !== norm(renderIndex(ctx))) {
    return [finding(meta.id, SEVERITY.ERROR, "INDEX.md is out of date with library.json + component frontmatter (a hand-edited generated file is an error at Gold, Standard sec 2.6 G4). Regenerate: node scripts/generators/gen-index.mjs . --write", { file: "INDEX.md", reqId: meta.reqId })];
  }
  return [];
}
