import { test } from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { rewriteTarget, emittedDirs, transform } from "../../site/scripts/gen-docs-site.mjs";

// Proves the Pattern S generator's link rewriting (site/scripts/gen-docs-site.mjs, ADR 0024 D2):
// a link to another published docs/ page becomes a base-absolute site route (so it resolves in the
// browser one URL level deeper), and a link to anything outside the published tree (the Standard, a
// skill reference, a script, library.json, an internal doc) becomes an absolute GitHub blob URL
// (which the clause-14.11 rendered-link guard skips). External/anchor links pass through untouched.
// rewriteTarget is pure path math (no filesystem reads), so synthetic source paths suffice.

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const BASE = "/agent-skills-toolkit";
const BLOB = "https://github.com/product-on-purpose/agent-skills-toolkit/blob/main";
// A real-shaped source path under the public docs tree; the files need not exist.
const SRC = path.join(REPO_ROOT, "docs", "how-to", "build-a-hook.md");

test("a sibling published doc becomes a base-absolute site route", () => {
  assert.equal(rewriteTarget("../reference/gold-checks.md", SRC), `${BASE}/reference/gold-checks/`);
});

test("a same-quadrant bare link becomes a site route", () => {
  assert.equal(
    rewriteTarget("climb-from-bronze-to-silver.md", SRC),
    `${BASE}/how-to/climb-from-bronze-to-silver/`,
  );
});

test("an #anchor is preserved on a rewritten site route", () => {
  assert.equal(rewriteTarget("../reference/gold-checks.md#g7", SRC), `${BASE}/reference/gold-checks/#g7`);
});

test("a link to the Standard (outside the published tree) becomes a GitHub blob URL", () => {
  assert.equal(rewriteTarget("../../STANDARD.md", SRC), `${BLOB}/STANDARD.md`);
});

test("a link to a skill reference becomes a GitHub blob URL", () => {
  assert.equal(
    rewriteTarget("../../skills/askit-evaluate/SKILL.md", SRC),
    `${BLOB}/skills/askit-evaluate/SKILL.md`,
  );
});

test("a non-markdown repo file (library.json) becomes a GitHub blob URL", () => {
  assert.equal(rewriteTarget("../../library.json", SRC), `${BLOB}/library.json`);
});

test("a docs/internal page is NOT a site route (it is not published) - blob URL instead", () => {
  assert.equal(
    rewriteTarget("../internal/decisions/0024-documentation-depth-and-discoverability.md", SRC),
    `${BLOB}/docs/internal/decisions/0024-documentation-depth-and-discoverability.md`,
  );
});

test("external, mailto, and pure-anchor links pass through unchanged", () => {
  assert.equal(rewriteTarget("https://example.com/x", SRC), "https://example.com/x");
  assert.equal(rewriteTarget("mailto:hi@example.com", SRC), "mailto:hi@example.com");
  assert.equal(rewriteTarget("#section", SRC), "#section");
});

test("a link to a published quadrant directory becomes a GitHub tree URL (no on-site index exists)", () => {
  // docs/explanation/faq.md links to ../how-to/ and ../reference/ as section pointers; an
  // autogenerated quadrant has no index page, so the canonical target is the GitHub tree view.
  const faq = path.join(REPO_ROOT, "docs", "explanation", "faq.md");
  const TREE = "https://github.com/product-on-purpose/agent-skills-toolkit/tree/main";
  assert.equal(rewriteTarget("../how-to/", faq), `${TREE}/docs/how-to/`);
  assert.equal(rewriteTarget("../reference/", faq), `${TREE}/docs/reference/`);
});

test("a target that escapes the repo root is left untouched (no fabricated URL)", () => {
  assert.equal(rewriteTarget("../../../../etc/passwd", SRC), "../../../../etc/passwd");
});

test("frontmatter is split on a FULL-LINE close, not a substring (a body --- line is not the close)", () => {
  // The close must be the line that is exactly `---`. A `---note` line earlier in the body must NOT
  // be taken as the frontmatter delimiter, or body links before it would be missed.
  const content = [
    "---",
    'title: "X"',
    "---",
    "",
    "See [the standard](../../STANDARD.md).",
    "",
    "---note: not a delimiter",
  ].join("\n");
  const out = transform(content, SRC);
  // frontmatter preserved verbatim; body link rewritten to a blob URL.
  assert.ok(out.startsWith('---\ntitle: "X"\n---\n'), "frontmatter block preserved");
  assert.ok(out.includes(`${BLOB}/STANDARD.md`), "body link after frontmatter is rewritten");
});

test("a ~~~ line does not close a ``` fence, and links inside the fence are not rewritten", () => {
  const content = [
    'A real link: [a](../reference/gold-checks.md).',
    "```md",
    "~~~",
    "Example in docs: [b](../reference/silver-checks.md)",
    "```",
    "Another real link: [c](../reference/silver-checks.md).",
  ].join("\n");
  const out = transform(content, SRC);
  // The two real links (outside the fence) are rewritten to site routes.
  assert.ok(out.includes(`${BASE}/reference/gold-checks/`), "pre-fence link rewritten");
  assert.ok(out.includes(`${BASE}/reference/silver-checks/).`), "post-fence link rewritten");
  // The example link INSIDE the fence is left verbatim (the inner ~~~ did not close the ``` fence).
  assert.ok(out.includes("[b](../reference/silver-checks.md)"), "in-fence link untouched");
});

test("CRLF source: an info-string fence opener and bare closer are detected, links after are rewritten", () => {
  // Regression for the CRLF bug: "```json\r" must register as the OPEN and "```\r" as the CLOSE, so a
  // link AFTER the fence is rewritten (not skipped as still-in-fence). Source docs are CRLF on Windows.
  const content = [
    "```json",
    '{ "a": 1 }',
    "```",
    "",
    "See [the standard](../../STANDARD.md).",
  ].join("\r\n");
  const out = transform(content, SRC);
  assert.ok(out.includes(`${BLOB}/STANDARD.md`), "link after a CRLF fence must be rewritten");
  assert.ok(out.includes('{ "a": 1 }'), "in-fence content preserved");
});

test("CRLF source: a reference-style link definition is rewritten (not left as a raw relative target)", () => {
  // Regression for the CRLF reference-def bug: rewriteBodyLinks must split on /\r?\n/ so the
  // `[label]: target` line does not retain a trailing \r the definition regex cannot consume, which
  // would leave the relative target un-rewritten and browser-broken on the published site.
  const content = [
    "See [the standard][std] for the rules.",
    "",
    "[std]: ../../STANDARD.md",
    "", // a trailing line: the def line is now FOLLOWED by a CRLF, so under split('\n') it keeps a \r
  ].join("\r\n");
  const out = transform(content, SRC);
  // This must FAIL against the pre-fix split('\n') code: the def line carries a trailing \r the
  // reference-def regex cannot consume, so the target is left un-rewritten. (A def on the LAST line
  // has no trailing \r and would match even pre-fix, which is why the trailing line is load-bearing.)
  assert.ok(out.includes(`[std]: ${BLOB}/STANDARD.md`), "the CRLF reference-style definition must be rewritten to a blob URL");
  assert.ok(!out.includes("[std]: ../../STANDARD.md"), "the raw relative reference target must not survive");
});

test("emittedDirs returns the public quadrants and never docs/internal", () => {
  const dirs = emittedDirs();
  assert.ok(dirs.includes("how-to"), `expected how-to in ${dirs.join(", ")}`);
  assert.ok(dirs.includes("reference"));
  assert.ok(dirs.includes("explanation"));
  assert.ok(dirs.includes("tutorials"));
  assert.ok(!dirs.includes("internal"), "docs/internal must never be emitted to the site");
});
